name: Run-Tests

on: push

jobs:
  run-test:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: install packages
        run: npm i --prefix src

      - name: Run tests
        run: npm run test --prefix src