name: Run-Tests

on: push

jobs:
  run-test:
    name: running tests
    runs-on: ubuntu-latest

    steps:
      - name: install packages
        run: cd src && npm i

      - name: Run tests
        run: npm run test